"""empty message

Revision ID: 0348c1525e53
Revises: fe985d5d9fa9
Create Date: 2024-05-13 06:20:20.770393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0348c1525e53'
down_revision = 'fe985d5d9fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('orders_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('orders_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key('orders_ibfk_2', 'order_tracking', ['order_id'], ['order_id'])
        batch_op.create_foreign_key('orders_ibfk_3', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('orders_ibfk_1', 'food_items', ['item_id'], ['item_id'])
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
