"""empty message

Revision ID: 418ddcb13bc2
Revises: 0348c1525e53
Create Date: 2024-05-13 06:23:50.841940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418ddcb13bc2'
down_revision = '0348c1525e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
