"""changed order_tracking

Revision ID: 87161d2a58aa
Revises: d6cf8069f1de
Create Date: 2024-05-05 18:26:11.572411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87161d2a58aa'
down_revision = 'd6cf8069f1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.drop_index('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_tracking', schema=None) as batch_op:
        batch_op.create_index('status', ['status'], unique=True)

    # ### end Alembic commands ###
