"""changed orders

Revision ID: fe985d5d9fa9
Revises: 87161d2a58aa
Create Date: 2024-05-05 18:27:32.791764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe985d5d9fa9'
down_revision = '87161d2a58aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('total_price', ['total_price'], unique=True)

    # ### end Alembic commands ###
